### PR TITLE
Kill plugin

### PR DESCRIPTION
**Pull request by timja**
on hold till next weekly release (2.323)

See https://github.com/jenkinsci/jenkins/pull/5926

### CODE REVIEW

**Review by jglick — APPROVED** [review]

**Comment by timja** [comment]
ready now @jglick

**Comment by jglick** [comment]
Do you need help merging & releasing?

**Comment by timja** [comment]
Yes I don’t have release here and you do, but happy to add myself if you wish

**Comment by jglick** [comment]
I will try to release it.

**Comment by jglick** [comment]
Done.

**Pull request merged**
