### PR TITLE
Forward compatibility with modern buttons

### PR DESCRIPTION
**Pull request by timja**
Unblocks https://github.com/jenkinsci/jenkins/pull/5897

See https://github.com/jenkinsci/acceptance-test-harness/pull/709#discussion_r744820260

cc @jglick

### CODE REVIEW

**Comment by jglick** [comment]
WDYT about simply inlining this functionality into Jenkins core? Other than very slightly larger HTML, I do not see any downside, and it would make ATH easier to maintain. (Might also be useful for HtmlUnit tests from `JenkinsRule`.)

**Comment by timja** [comment]
> WDYT about simply inlining this functionality into Jenkins core? Other than very slightly larger HTML, I do not see any downside, and it would make ATH easier to maintain. (Might also be useful for HtmlUnit tests from `JenkinsRule`.)

Hmm not sure, likely a fair bit of html bloat.

**Comment by timja** [comment]
The other option would be to convert this plugin to enabling the core functionality?

and allow enabling it with a system property.

I’d be happier with that, any thought?

**Comment by jglick** [comment]
> convert this plugin to enabling the core functionality?
> 
> and allow enabling it with a system property.

That sounds reasonable too.

**Comment by jglick** [comment]
Obsolete.

**Pull request closed without merging**
